# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

# General Ruby Style
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/tasks/**/*"

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 100
  Exclude:
    - "spec/**/*"

# RSpec specific configuration
RSpec/DescribeClass:
  Exclude:
    - "spec/requests/**/*"

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 100

RSpec/NestedGroups:
  Max: 4

RSpec/ImplicitExpect:
  EnforcedStyle: is_expected

RSpec/ContextWording:
  Enabled: false

# Rails specific configuration
Rails/DynamicFindBy:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/NotNullColumn:
  Enabled: false
